# Generated by Django 3.0.2 on 2020-02-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255, null=True, verbose_name='チーム')),
                ('dominant', models.CharField(choices=[('', '右'), ('*', '左'), ('+', '両')], max_length=2, null=True, verbose_name='席')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('b_num', models.IntegerField(verbose_name='打席')),
                ('point', models.IntegerField(verbose_name='得点')),
                ('hit', models.IntegerField(verbose_name='安打')),
                ('hit2', models.IntegerField(verbose_name='二塁打')),
                ('hit3', models.IntegerField(verbose_name='三塁打')),
                ('homerun', models.IntegerField(verbose_name='本塁打')),
                ('b_point', models.IntegerField(verbose_name='打点')),
                ('steal', models.IntegerField(verbose_name='盗塁')),
                ('steal_out', models.IntegerField(verbose_name='盗塁刺')),
                ('s_hit', models.IntegerField(verbose_name='犠打')),
                ('s_fly', models.IntegerField(verbose_name='犠飛')),
                ('fourball', models.IntegerField(verbose_name='四球')),
                ('intent_four', models.IntegerField(verbose_name='故意四')),
                ('deadball', models.IntegerField(verbose_name='死球')),
                ('s_out', models.IntegerField(verbose_name='三振')),
                ('double_out', models.IntegerField(verbose_name='併殺打')),
            ],
        ),
    ]
