# Generated by Django 2.2.5 on 2020-03-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('games', models.IntegerField(verbose_name='試合数')),
                ('team', models.CharField(choices=[('L', '埼玉西武ライオンズ'), ('H', '福岡ソフトバンクホークス'), ('E', '東北楽天ゴールデンイーグルス'), ('M', '千葉ロッテマリーンズ'), ('F', '北海道日本ハムファイターズ'), ('B', 'オリックス・バファローズ'), ('G', '読売ジャイアンツ'), ('DB', '横浜DeNAベイスターズ'), ('T', '阪神タイガース'), ('C', '広島東洋カープ'), ('D', '中日ドラゴンズ'), ('S', '東京ヤクルトスワローズ')], max_length=255, verbose_name='チーム')),
                ('handed', models.CharField(choices=[('', '右'), ('*', '左'), ('+', '両')], max_length=2, verbose_name='席')),
                ('plate_appearances', models.IntegerField(verbose_name='打席')),
                ('at_bats', models.IntegerField(verbose_name='打数')),
                ('runs', models.IntegerField(verbose_name='得点')),
                ('hits', models.IntegerField(verbose_name='安打')),
                ('hits2', models.IntegerField(verbose_name='二塁打')),
                ('hits3', models.IntegerField(verbose_name='三塁打')),
                ('homeruns', models.IntegerField(verbose_name='本塁打')),
                ('runs_batted_in', models.IntegerField(verbose_name='打点')),
                ('steals', models.IntegerField(verbose_name='盗塁')),
                ('caught_steals', models.IntegerField(verbose_name='盗塁死')),
                ('sacrifice_hits', models.IntegerField(verbose_name='犠打')),
                ('sacrifice_flies', models.IntegerField(verbose_name='犠飛')),
                ('bases_on_balls', models.IntegerField(verbose_name='四球')),
                ('intentional_walks', models.IntegerField(verbose_name='故意四')),
                ('hits_by_pitch', models.IntegerField(verbose_name='死球')),
                ('strike_outs', models.IntegerField(verbose_name='三振')),
                ('double_plays', models.IntegerField(verbose_name='併殺打')),
                ('batting_average', models.FloatField(verbose_name='打率')),
                ('on_base_percentage', models.FloatField(verbose_name='出塁率')),
                ('slugging_percentage', models.FloatField(verbose_name='長打率')),
                ('ops', models.FloatField(verbose_name='OPS')),
                ('stolen_bases_percentage', models.FloatField(verbose_name='盗塁成功率')),
                ('year', models.IntegerField(verbose_name='年度')),
            ],
        ),
        migrations.CreateModel(
            name='Fielding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('L', '埼玉西武ライオンズ'), ('H', '福岡ソフトバンクホークス'), ('E', '東北楽天ゴールデンイーグルス'), ('M', '千葉ロッテマリーンズ'), ('F', '北海道日本ハムファイターズ'), ('B', 'オリックス・バファローズ'), ('G', '読売ジャイアンツ'), ('DB', '横浜DeNAベイスターズ'), ('T', '阪神タイガース'), ('C', '広島東洋カープ'), ('D', '中日ドラゴンズ'), ('S', '東京ヤクルトスワローズ')], max_length=255, verbose_name='チーム')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('handed', models.CharField(choices=[('', '右'), ('*', '左')], max_length=2, verbose_name='投')),
                ('position', models.CharField(max_length=255, verbose_name='守備位置')),
                ('games', models.IntegerField(verbose_name='試合')),
                ('put_outs', models.IntegerField(verbose_name='刺殺')),
                ('assists', models.IntegerField(verbose_name='補殺')),
                ('errors', models.IntegerField(verbose_name='失策')),
                ('double_plays', models.IntegerField(verbose_name='併殺')),
                ('passed_balls', models.IntegerField(default=0, null=True, verbose_name='捕逸')),
                ('fielding_average', models.FloatField(verbose_name='守備率')),
                ('year', models.IntegerField(verbose_name='年度')),
            ],
        ),
        migrations.CreateModel(
            name='Pitching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('L', '埼玉西武ライオンズ'), ('H', '福岡ソフトバンクホークス'), ('E', '東北楽天ゴールデンイーグルス'), ('M', '千葉ロッテマリーンズ'), ('F', '北海道日本ハムファイターズ'), ('B', 'オリックス・バファローズ'), ('G', '読売ジャイアンツ'), ('DB', '横浜DeNAベイスターズ'), ('T', '阪神タイガース'), ('C', '広島東洋カープ'), ('D', '中日ドラゴンズ'), ('S', '東京ヤクルトスワローズ')], max_length=255, verbose_name='チーム')),
                ('handed', models.CharField(choices=[('', '右'), ('*', '左')], max_length=2, verbose_name='投')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('games', models.IntegerField(verbose_name='登板')),
                ('earned_run_average', models.FloatField(verbose_name='防御率')),
                ('wins', models.IntegerField(verbose_name='勝利')),
                ('loses', models.IntegerField(verbose_name='敗戦')),
                ('saves', models.IntegerField(verbose_name='セーブ')),
                ('holds', models.IntegerField(verbose_name='ホールド')),
                ('completes', models.IntegerField(verbose_name='完投')),
                ('shut_out_wins', models.IntegerField(verbose_name='完封')),
                ('no_BB_completes', models.IntegerField(verbose_name='無四球')),
                ('winning_percentage', models.FloatField(verbose_name='勝率')),
                ('batters_faced', models.IntegerField(verbose_name='対戦打者')),
                ('outs', models.IntegerField(verbose_name='獲得アウト')),
                ('innings', models.FloatField(verbose_name='イニング')),
                ('hits', models.IntegerField(verbose_name='被安打')),
                ('homeruns', models.IntegerField(verbose_name='被本塁打')),
                ('bases_on_balls', models.IntegerField(verbose_name='与四球')),
                ('intentional_walks', models.IntegerField(verbose_name='与故意四')),
                ('hits_by_pitch', models.IntegerField(verbose_name='与死球')),
                ('strike_outs', models.IntegerField(verbose_name='奪三振')),
                ('wild_pitches', models.IntegerField(verbose_name='暴投')),
                ('balks', models.IntegerField(verbose_name='ボーク')),
                ('runs', models.IntegerField(verbose_name='失点')),
                ('earned_runs', models.IntegerField(verbose_name='自責点')),
                ('year', models.IntegerField(verbose_name='年度')),
            ],
        ),
    ]
