# Generated by Django 2.2.5 on 2020-02-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fielding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255, verbose_name='チーム')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('handed', models.CharField(max_length=2, verbose_name='投')),
                ('position', models.CharField(max_length=255, verbose_name='守備位置')),
                ('games', models.IntegerField(verbose_name='試合')),
                ('put_outs', models.IntegerField(verbose_name='刺殺')),
                ('assists', models.IntegerField(verbose_name='補殺')),
                ('errors', models.IntegerField(verbose_name='失策')),
                ('double_plays', models.IntegerField(verbose_name='併殺')),
                ('passed_balls', models.IntegerField(default=0, null=True, verbose_name='捕逸')),
            ],
        ),
        migrations.AlterField(
            model_name='batting',
            name='handed',
            field=models.CharField(choices=[('', '右'), ('*', '左'), ('+', '両')], max_length=2, verbose_name='席'),
        ),
        migrations.AlterField(
            model_name='batting',
            name='team',
            field=models.CharField(max_length=255, verbose_name='チーム'),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='handed',
            field=models.CharField(choices=[('', '右'), ('*', '左')], max_length=2, verbose_name='投'),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='team',
            field=models.CharField(max_length=255, verbose_name='チーム'),
        ),
    ]
